[package]
name = "_7_2_restaurant"
version = "0.1.0"
authors = ["Dima <dv@kappacoding.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "restaurant"
path = "src/lib.rs"

[dependencies]
